name: Generate PR List

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

permissions: write-all

jobs:
  generate-pr-list:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get PR list
        run: |
          HEAD=$(git rev-parse HEAD)
          BASE=$(git rev-parse {{ github.base_ref }})
          
          PR_LIST=$(git log --pretty=format:"%s" $BASE..$HEAD | grep -iE '#[0-9]+')
          COMMENT=''
          for PR in $PR_LIST; do
          COMMENT="$COMMENT\n- $PR"
          done
          echo "::set-output name=pr_list::$(echo -e "$PR_LIST")"
      - name: Comment on PR
        uses: unsplash/comment-on-pr@v1.3.0
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: |
            [PR list]:
            ${{ steps.generate-pr-list.outputs.pr_list }}
          delete_prev_regex_msg: '\[PR list\]'
